config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'
  resources :articles, only: [ :index, :show, :new, :create ]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, :url, presence: true
  include PgSearch::Model
  pg_search_scope :search_by_title_and_body, against: [:title, :body]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
require 'open-uri'
require 'nokogiri'

class ArticlesController < ApplicationController
  def index
    if params[:query].present?
      @articles = Article.search_by_title_and_body("#{params[:query]}")
    else
      @articles = Article.all
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    html_file = URI.open(@article.url).read
    html_doc = Nokogiri::HTML(html_file)
    @article.body = html_doc.search('h1').text + "," + html_doc.search('h2').text + "," + html_doc.search('h3').text
    html_doc.search('article').each do |element|
      wpm = 225
      words = element.text.split(/\s+/).length
      @article.reading_time = (words / wpm).to_s
    end
    @article.short_url = (@article.url.match(/^((http[s]?|ftp):\/)?\/?([^:\/\s]+)((\/\w+)*\/)([\w\-\.]+[^#?\s]+)(.*)?(#[\w\-]+)?$/))[3]
    if @article.save
      redirect_to articles_path
    else
      render :new
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :url)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<div class="container">
<%= simple_form_for [article] do |f| %>
    <%= f.input :title, required: true, placeholder: "What is the article title?"%>
    <%= f.input :url, required: true, placeholder: "What is the article url?" %>
    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/articles/index.html.erb
<h1 class="text-center">Articles Dashboard</h1>
<div class="container">
  <%= form_tag articles_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find an article"
    %>
    <%= submit_tag "Search", class: "btn btn-primary" %>
  <% end %>
<a><%= link_to "Add an article", new_article_path, class:"btn btn-primary mt-2" %></a>
  <ul>
  <% @articles.each do |article| %>
    <li>
      <h1><%= link_to article.title, article_path(article) %> </h1>
      <a href="<%= article.url %>"><%= article.short_url %></a>
      <% if article.reading_time.to_i > 1 %>
        <p><i>Reading time: <%= article.reading_time %> minutes</i></p>
      <% else %>
        <p><i>Reading time: less than a minute</i></p>
      <% end %>
    </li>
  <% end %>
  </ul>

  <% if params[:query].present? %>
    <a><%= link_to "Back to articles", articles_path, class:"btn btn-primary" %></a>
  <% end %>
</div>

app/views/articles/new.html.erb
<%= render "form", article: @article %>

app/views/articles/show.html.erb
<div class="container mt-3">
  <h1><%= @article.title %></h1>

  <ul>
  <% @article.body.split(",").each do |word| %>
      <li><%= word %></li>
  <% end %>
  </ul>


  <a href="<%= @article.url %>"><%= @article.short_url %></a>
  <% if @article.reading_time.to_i > 1 %>
      <p><i>Reading time: <%= @article.reading_time %> minutes</i></p>
    <% else %>
      <p><i>Reading time: less than a minute</i></p>
    <% end %>
  <a><%= link_to "Go back", articles_path %></a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSearch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>